/* ============================================================
   SCHEMA — the single source of truth for the GDD Builder.
   Add a new object to `initialSections`, or a new entry to any
   `subsections` array, and the UI + generated document pick it
   up automatically — no other code changes needed.
   ============================================================ */
// Helper: turn a plain string list into {label, definition} objects.
// Used for subsections that don't have researched definitions yet —
// definition starts empty, so no tooltip shows until one is added.
const plain = (labels) => labels.map((label) => ({ label, definition: "" }));

const initialSections = [
  {
    id: "mechanics",
    title: "Gameplay Mechanics",
    subsections: [
      {
        id: "core_mechanics",
        label: "Core Mechanics",
        options: [
          { label: "Movement (Walk/Run)", definition: "Basic locomotion allowing the player to traverse the game space at variable speed." },
          { label: "Jump", definition: "A vertical traversal action that clears gaps, obstacles, or reaches higher ground." },
          { label: "Melee Attack", definition: "A close-range offensive action using direct-contact weapons or unarmed strikes." },
          { label: "Ranged Attack", definition: "An offensive action that damages targets at a distance using projectiles or hitscan weapons." },
          { label: "Block/Parry", definition: "A defensive action that mitigates or negates incoming damage when timed or held correctly." },
          { label: "Dodge/Evade", definition: "A quick directional movement that avoids incoming damage or attacks, often with brief invulnerability." },
          { label: "Sprint", definition: "A temporary speed boost to movement, typically limited by a stamina resource." },
          { label: "Crouch/Prone", definition: "Lowering the character's stance to reduce visibility, fit through spaces, or improve accuracy." },
          { label: "Climb", definition: "Vertical or angled traversal along surfaces such as ladders, walls, or ledges." },
          { label: "Swim", definition: "Movement through liquid environments, often governed by different controls than movement on land." },
          { label: "Interact", definition: "A general-purpose action for engaging with objects, NPCs, or the environment, such as opening or activating something." },
          { label: "Grab/Carry", definition: "Picking up and physically moving objects or characters within the world." },
          { label: "Aim", definition: "Directing a weapon or tool precisely before or during an action, typically affecting accuracy." },
          { label: "Reload", definition: "Restocking ammunition or a limited resource for a weapon or tool before it can be used again." },
          { label: "Aerial Mobility (Double Jump/Air Dash)", definition: "Extended mid-air movement options that let the player alter trajectory or gain height after leaving the ground." },
          { label: "Grapple/Hook", definition: "A traversal mechanic that pulls the player toward, or lets them swing from, a fixed anchor point." },
          { label: "Stealth/Sneak", definition: "Moving while minimizing detection by enemies or sensors, usually tied to noise level or visibility." },
          { label: "Build/Place", definition: "Constructing or placing structures, objects, or terrain pieces within the world." },
          { label: "Craft", definition: "Combining materials or components according to a recipe to create a new item." },
          { label: "Gather/Harvest", definition: "Collecting resources from the environment, such as plants, ore, or loot." },
          { label: "Trade/Barter", definition: "Exchanging items, currency, or resources with NPCs or other players." },
          { label: "Dialogue Choice", definition: "Selecting from branching conversation options that affect narrative outcomes or relationships." },
          { label: "Cast/Channel Ability", definition: "Activating a spell or special ability, often requiring a resource cost, cooldown, or charge time." },
          { label: "Summon", definition: "Calling forth an ally, creature, or object to fight or assist alongside the player." },
          { label: "Transform/Shapeshift", definition: "Changing the player character's form, temporarily or permanently altering their abilities or stats." },
          { label: "Push/Pull", definition: "Physically manipulating objects in the environment by applying directional force." },
          { label: "Throw", definition: "Launching an item, weapon, or projectile at a target location." },
          { label: "Heal/Restore", definition: "Recovering health, resources, or a status condition through an item, ability, or timed action." },
          { label: "Drive/Pilot", definition: "Taking control of a vehicle, mount, or mechanized unit instead of moving the character directly." },
          { label: "Time Manipulation", definition: "Slowing, stopping, rewinding, or fast-forwarding time as a direct, player-triggered action." },
        ],
      },
      {
        id: "secondary_mechanics",
        label: "Secondary Mechanics",
        options: [
          { label: "Inventory Management", definition: "A system for storing, organizing, and equipping the items the player collects." },
          { label: "Crafting System", definition: "Combining materials or components to create new items, gear, or consumables." },
          { label: "Dialogue System", definition: "Structured conversations with NPCs, often including branching choices that affect outcomes." },
          { label: "Stealth Mechanics", definition: "Supporting systems for avoiding detection, such as noise meters, visibility indicators, or patrol patterns." },
          { label: "Skill Tree/Talent System", definition: "A branching set of unlockable upgrades or abilities the player chooses from over time." },
          { label: "Companion/Pet System", definition: "Managing an AI ally or creature that assists, follows, or can be commanded by the player." },
          { label: "Reputation/Faction System", definition: "Tracking the player's standing with groups or factions that changes how those groups behave toward them." },
          { label: "Relationship/Affinity System", definition: "Tracking individual NPC relationships that shift based on player choices, gifts, or dialogue." },
          { label: "Quest/Journal Log", definition: "A system for tracking active, completed, and available objectives." },
          { label: "Fast Travel", definition: "A shortcut system letting players instantly move between previously discovered locations." },
          { label: "Housing/Base Building", definition: "Player-owned spaces that can be customized, decorated, or expanded over time." },
          { label: "Mount/Vehicle System", definition: "Managing rideable creatures or vehicles used for faster or specialized traversal." },
          { label: "Weather/Day-Night Cycle", definition: "Environmental systems that change conditions over time and may affect visibility, enemy behavior, or available actions." },
          { label: "Economy/Currency System", definition: "Managing money or trade goods used to buy, sell, or upgrade throughout the game." },
          { label: "Shop/Vendor System", definition: "Interfaces for buying and selling items with NPC merchants or other players." },
          { label: "Cooking/Alchemy System", definition: "Combining ingredients according to recipes to create food, potions, or temporary buffs." },
          { label: "Enchanting/Upgrading System", definition: "Enhancing existing gear with additional stats, effects, or higher rarity tiers." },
          { label: "Photo Mode", definition: "A non-gameplay feature that lets players pause the action and compose or capture in-game scenes." },
          { label: "Codex/Lore Collection", definition: "Collectible in-world text or item entries that expand on the setting's backstory without affecting core progression." },
          { label: "Achievement/Trophy System", definition: "Tracking optional milestones or challenges that exist outside the main progression path." },
          { label: "Minigame System", definition: "Self-contained smaller games embedded within the larger game, such as lockpicking or fishing." },
          { label: "Emote/Social Gesture System", definition: "Non-verbal communication options for expressing emotion or interacting socially with other players." },
          { label: "Difficulty/Assist Options", definition: "Adjustable settings that modify the game's challenge level or improve accessibility." },
          { label: "Weapon/Gear Customization", definition: "Modifying the appearance or stats of equipment through attachments, skins, or visual dyes." },
          { label: "Party/Squad Management", definition: "Assembling and directing a group of characters as a coordinated unit." },
          { label: "Notoriety/Wanted System", definition: "Tracking escalating law-enforcement or NPC response based on the player's recent actions." },
          { label: "Map/Cartography System", definition: "Revealing, marking, or annotating a world map as the player explores it." },
        ],
      },
      {
        id: "mechanic_interactions",
        label: "Mechanic Interactions",
        options: [
          { label: "Elemental Combination", definition: "Two elemental effects (fire, water, electricity, ice, etc.) combine to produce a new effect distinct from either alone." },
          { label: "Environmental Combo", definition: "A mechanic is applied to the environment itself, producing a secondary effect such as spreading fire or flooding an area." },
          { label: "Status Effect Stacking", definition: "Multiple status effects applied to the same target combine, amplify, or interact to produce a compounded outcome." },
          { label: "Chain Reaction", definition: "Triggering one effect causes it to cascade outward, setting off further effects on nearby targets or objects." },
          { label: "Synergy Combo", definition: "Combining specific abilities or items causes their effects to mutually amplify one another beyond their individual value." },
          { label: "Counter/Weakness Interaction", definition: "A specific mechanic is deliberately strong against, or negated by, another in a rock-paper-scissors-style relationship." },
          { label: "Resource Conversion", definition: "Using one mechanic transforms one resource type into another, such as converting health into mana." },
          { label: "Tool-Environment Interaction", definition: "A mechanic-based tool produces a specific, designed reaction when used on a matching environmental object." },
          { label: "Momentum Transfer", definition: "Velocity or force generated by one mechanic carries over and affects the outcome of a subsequent action." },
          { label: "Trigger-Response Interaction", definition: "Performing one mechanic activates an automated response from another system, such as a trap or switch." },
          { label: "Crowd Control Combo", definition: "An immobilizing or disabling mechanic is paired with a damage or follow-up mechanic to guarantee its effect lands." },
          { label: "Physics-Based Interaction", definition: "Mechanics interact through simulated physics, such as force, gravity, or collision, rather than scripted rules." },
          { label: "Timing-Based Interaction", definition: "Performing inputs in sequence within a specific time window combines them into a distinct, higher-value result." },
          { label: "Resource Denial Interaction", definition: "One mechanic removes or blocks a resource that another mechanic, often an opponent's, depends on to function." },
          { label: "Multiplayer Synergy Combo", definition: "Two or more players' individually-controlled mechanics combine to create an effect neither could produce alone." },
          { label: "State Transformation Interaction", definition: "One mechanic changes the state of an object or character in a way that alters how other mechanics subsequently affect it." },
          { label: "Amplification Interaction", definition: "One mechanic increases the potency, duration, or area of another mechanic's effect." },
          { label: "Suppression Interaction", definition: "One mechanic reduces, delays, or disables the effectiveness of another mechanic while active." },
          { label: "Positional Interaction", definition: "The spatial relationship between two mechanics, such as flanking or backstabbing, changes the outcome of an action." },
          { label: "Cascading Failure Interaction", definition: "The failure of one mechanic triggers a negative chain of consequences across other interconnected systems." },
        ],
      },
      {
        id: "rules_constraints",
        label: "Rules and Constraints",
        options: [
          { label: "Stamina Limit", definition: "A depletable resource that restricts sustained physical actions until it regenerates." },
          { label: "Cooldown Timer", definition: "A fixed time delay required before an ability or action can be used again." },
          { label: "Ammo/Resource Limit", definition: "A finite consumable resource restricts how often a ranged or resource-based action can be performed." },
          { label: "Weight/Carry Limit", definition: "A cap on how much the player can carry before movement or actions are penalized." },
          { label: "Health/Life Limit", definition: "A finite health pool whose depletion ends the current attempt, life, or run." },
          { label: "Permadeath", definition: "Death is permanent and irreversible, typically ending the run or erasing progress entirely." },
          { label: "Time Limit", definition: "An action, encounter, or level must be completed within a fixed time window." },
          { label: "Action Point Limit", definition: "A per-turn budget of points restricts how many actions can be taken in a given turn." },
          { label: "Shared Resource Pool", definition: "Multiple abilities draw from, and are limited by, the same shared resource rather than independent ones." },
          { label: "Line of Sight Requirement", definition: "An action can only be performed if a clear, unobstructed sightline exists to the target." },
          { label: "Range Limit", definition: "An action can only affect targets within a fixed maximum distance." },
          { label: "Positional Requirement", definition: "An action requires the player to be in a specific location, stance, or facing to execute it." },
          { label: "Charge/Buildup Requirement", definition: "An action requires a period of charging or channeling before its effect is applied." },
          { label: "Cost/Currency Requirement", definition: "An action can only be performed if the player is able to pay an associated in-game cost." },
          { label: "Durability Limit", definition: "Equipment degrades with use and eventually breaks or becomes less effective." },
          { label: "Inventory Slot Limit", definition: "A fixed number of inventory slots restricts how many distinct items can be carried at once." },
          { label: "Level/Gear Gate", definition: "An action, item, or area is inaccessible until the player reaches a required level or gear threshold." },
          { label: "Fall Damage Rule", definition: "A rule defining whether, and how much, damage is inflicted when falling from height." },
          { label: "Friendly Fire Rule", definition: "A rule determining whether a player's actions can harm allies or teammates." },
          { label: "One-Life-Per-Run Rule", definition: "Progress resets to the start of the run upon death, though separate meta-progression may still persist." },
          { label: "Turn Order Constraint", definition: "Actions must occur in a fixed sequence determined by initiative or turn order rather than freely." },
          { label: "Sanity/Corruption Limit", definition: "A secondary resource that depletes or rises with use of certain mechanics, carrying negative consequences at its extreme." },
          { label: "Detection Threshold", definition: "A rule defining the point at which stealth-based actions fail and the player becomes noticed." },
          { label: "Global Cooldown", definition: "After using any ability, a brief shared window prevents using any other ability, regardless of its individual cooldown." },
          { label: "Difficulty-Scaled Constraint", definition: "A rule whose limits, such as damage, resources, or timers, shift based on the selected difficulty setting." },
        ],
      },
      {
        id: "edge_cases",
        label: "Edge Cases",
        options: [
          { label: "Action During Hitstun/Stagger", definition: "Whether the player can act, cancel, or is fully locked out while affected by hitstun or a stagger animation." },
          { label: "Action During Reload/Cast", definition: "Whether the player can move, aim, or switch actions while a reload or cast animation is still in progress." },
          { label: "Input During Cutscene/Cinematic", definition: "Whether player input can interrupt, skip, or bleed through into an active scripted cutscene." },
          { label: "Status Effect Stacking/Conflict", definition: "What happens when multiple instances of the same status effect, or two conflicting effects, are applied at once." },
          { label: "Simultaneous Death Resolution", definition: "Which outcome takes priority when the player and an enemy would both die on the same frame or turn." },
          { label: "Out-of-Bounds/Geometry Exploit", definition: "What happens when a player uses movement mechanics to reach unintended areas outside the designed play space." },
          { label: "Input Buffer Priority Conflict", definition: "When multiple inputs are queued in rapid succession, which one takes priority and how long the buffer window lasts." },
          { label: "Resource Underflow/Overflow", definition: "What happens when a single action would push a resource below zero or above its maximum cap." },
          { label: "Save/Load Mid-Action", definition: "What happens if the game is saved or loaded while an action, animation, or timer is mid-execution." },
          { label: "Overlapping Environmental Hazards", definition: "How two environmental hazards, or a hazard and an existing status effect, resolve when they overlap on the same target." },
          { label: "Simultaneous Trigger Collision", definition: "What happens when two or more triggered events, such as traps or scripted abilities, would fire at the exact same moment." },
          { label: "Death Mid-Ability/Channel", definition: "What happens to an ability's effect, cooldown, or resource cost if the character dies while it is active or channeling." },
          { label: "Overlapping Hitbox Resolution", definition: "How damage or effect resolution is determined when a single attack's hitbox overlaps multiple valid targets at once." },
          { label: "Clipping Through Geometry", definition: "What prevents, or governs, a fast-moving character from passing through walls, floors, or other solid geometry." },
          { label: "Interrupted Transformation/Shapeshift", definition: "Whether abilities can be queued, canceled, or interrupted while a character is mid-transformation." },
          { label: "Multiplayer Desync/Race Condition", definition: "How conflicting simultaneous actions from different players are resolved when network state briefly disagrees." },
          { label: "Ability Combo Cancel Window", definition: "Whether, and during which exact frames, one ability's animation can be canceled into another to chain a combo." },
          { label: "Zero-Duration/Instant Effect Conflict", definition: "How two instantaneous effects that would both resolve at the same instant are ordered and applied." },
          { label: "Friendly Fire Ambiguity", definition: "How area-of-effect or projectile actions resolve when both allies and enemies are caught in the same effect radius." },
          { label: "Edge-of-Map Physics Behavior", definition: "How physics-based mechanics behave when an object or character reaches the extreme boundary of the playable world." },
          { label: "Disconnection/Pause Mid-Encounter", definition: "What happens to an in-progress encounter, timer, or turn if a player disconnects or pauses mid-action." },
          { label: "AI Target Loss Mid-Behavior", definition: "How an enemy or companion AI resolves its current behavior when its active target becomes invalid or unreachable." },
        ],
      },
    ],
  },
  {
    id: "loops",
    title: "Gameplay Loops",
    subsections: [
      {
        id: "core_loop",
        label: "Core Loop",
        options: [
          { label: "Explore → Fight → Loot → Upgrade", definition: "The player explores an area, fights enemies encountered along the way, collects loot from them, and spends it to grow stronger — typical of action RPGs and looter-shooters." },
          { label: "Plant → Tend → Harvest → Sell", definition: "The player plants crops or resources, maintains them over time, harvests the result, and sells it for currency to reinvest — typical of farming and life sims." },
          { label: "Scout → Plan → Execute → Extract", definition: "The player scouts a target, plans an approach, executes the plan under risk, and extracts with the reward — typical of heist and extraction games." },
          { label: "Build → Defend → Upgrade", definition: "The player constructs defenses or a base, survives an attack against them, and upgrades before the next attempt — typical of tower defense and base-building games." },
          { label: "Gather → Craft → Equip", definition: "The player gathers raw materials, crafts them into usable items or gear, and equips the result to improve capability — typical of survival and crafting games." },
          { label: "Match → Score → Rank", definition: "The player competes in a discrete match, earns a score or result, and sees their standing shift — typical of competitive and PvP games." },
          { label: "Explore → Solve → Progress", definition: "The player explores a space, solves an obstacle or puzzle blocking the way, and advances as a result — typical of puzzle and adventure games." },
          { label: "Fight → Reward → Repeat", definition: "The player fights through a short run, earns a reward on completion or death, and immediately begins another attempt — typical of roguelikes and roguelites." },
          { label: "Move → Match → Clear", definition: "The player moves or arranges pieces to form matches, which clear from the board and trigger further effects — typical of match-3 and tile puzzle games." },
          { label: "Race → Place → Upgrade", definition: "The player races against opponents or the clock, earns a placement or reward, and spends it on upgrades for the next race — typical of racing games." },
          { label: "Build → Manage → Optimize", definition: "The player builds out a system or settlement, manages its ongoing needs, and continually optimizes it for efficiency — typical of city builders and management sims." },
          { label: "Sneak → Eliminate → Evade", definition: "The player moves undetected toward a target, eliminates or bypasses it, and evades any resulting alert — typical of stealth games." },
          { label: "Collect → Trade → Expand", definition: "The player collects goods, trades them for profit or advantage, and reinvests to expand their operation — typical of trading and economy sims." },
          { label: "Train → Battle → Evolve", definition: "The player trains a creature or unit, battles with it to prove its strength, and evolves or upgrades it as a result — typical of creature-collector games." },
          { label: "Shoot → Reload → Advance", definition: "The player engages enemies with ranged combat, manages ammunition through reloads, and advances once the area is clear — typical of shooters." },
          { label: "Dialogue → Choice → Consequence", definition: "The player engages in dialogue, makes a meaningful choice, and experiences a narrative consequence that shapes what follows — typical of narrative and visual novel games." },
          { label: "Dig → Return → Sell", definition: "The player descends into a mine or dungeon to gather resources, returns to a safe hub, and sells the haul before heading back down — typical of mining and dungeon-crawler games." },
          { label: "Wave → Survive → Upgrade", definition: "The player survives an escalating wave of enemies and spends earned resources on upgrades before the next wave begins — typical of horde survival games." },
          { label: "Investigate → Deduce → Confront", definition: "The player gathers clues through investigation, deduces a conclusion from them, and confronts a suspect or solution — typical of mystery and detective games." },
          { label: "Command → Execute → Adapt", definition: "The player issues commands to units, watches them execute, and adapts their strategy based on the outcome — typical of RTS and strategy games." },
        ],
      },
      {
        id: "macro_loop",
        label: "Macro Loop",
        options: [
          { label: "Complete Level → Unlock Next", definition: "Finishing a level immediately unlocks and grants access to the next one in sequence." },
          { label: "Clear Dungeon → Boss Fight → Reward", definition: "The player clears a self-contained dungeon, faces its boss, and receives a reward tied specifically to that dungeon." },
          { label: "Win Match → Season Progress", definition: "The outcome of a single match contributes toward progress in an overarching competitive season." },
          { label: "Finish Quest Chain → New Region Unlocked", definition: "Completing a connected series of quests opens up a previously inaccessible region of the world." },
          { label: "Defeat Area Boss → World State Changes", definition: "Defeating a major boss permanently alters the state of the surrounding area, such as opening paths or changing enemy spawns." },
          { label: "Complete Act → Story Chapter Advances", definition: "Finishing a defined act or section of content advances the overarching narrative to its next chapter." },
          { label: "Clear Wave Set → Difficulty Tier Increases", definition: "Surviving a full set of enemy waves increases the difficulty tier for subsequent waves or runs." },
          { label: "Finish Expedition → Return to Hub", definition: "Completing an out-in-the-world expedition returns the player to a central hub to prepare for the next one." },
          { label: "Win Tournament Round → Advance Bracket", definition: "Winning a round in a tournament structure advances the player to the next bracket stage." },
          { label: "Complete Contract → Reputation Increases", definition: "Fulfilling a discrete job or contract raises the player's standing with the party who issued it." },
          { label: "Clear Floor → Descend to Next Floor", definition: "Clearing all objectives or threats on a floor allows descent to the next, progressively harder floor." },
          { label: "Finish Build Phase → Enter Combat Phase", definition: "A dedicated construction or preparation phase concludes and transitions the game into an active combat phase." },
          { label: "Win Territory → Map Control Expands", definition: "Successfully contesting a territory expands the area of the map under the player's control." },
          { label: "Complete Research → New Tech Unlocked", definition: "Finishing a research project unlocks a new piece of technology, unit, or capability." },
          { label: "Finish Season Event → Rewards Distributed", definition: "The conclusion of a time-limited seasonal event triggers distribution of rewards based on participation or rank." },
          { label: "Clear Raid → Loot Tier Unlocked", definition: "Successfully completing a raid unlocks access to a higher tier of loot for future runs." },
          { label: "Win Race → Championship Standings Update", definition: "The result of an individual race updates the player's position in an overarching championship standing." },
          { label: "Complete Chapter → New Mechanic Introduced", definition: "Finishing a chapter of content introduces a new mechanic that expands what the player can do going forward." },
        ],
      },
      {
        id: "meta_loop",
        label: "Meta Loop",
        options: [
          { label: "Prestige/New Game Plus System", definition: "The player resets their progress in exchange for a permanent bonus or harder, remixed replay of the content." },
          { label: "Battle Pass/Season Pass Progression", definition: "Ongoing play earns points toward a tiered track of rewards tied to a limited-time season." },
          { label: "Skill Tree Mastery", definition: "The player gradually invests earned points across sessions to fully unlock a branching tree of permanent upgrades." },
          { label: "Zone/Region Unlock Progression", definition: "New areas of the world become accessible over time as the player meets progression requirements." },
          { label: "Base/Hub Expansion Over Time", definition: "The player's home base or hub grows and unlocks new features gradually across many sessions." },
          { label: "Collection Completion", definition: "The player works toward completing a full set of collectibles, codex entries, or catalogued items over time." },
          { label: "Account/Player Level Progression", definition: "A persistent player-wide level increases from all activity, independent of any single character or run." },
          { label: "Gear Tier Progression", definition: "The player climbs a long-term ladder of increasingly powerful equipment tiers across many sessions." },
          { label: "Faction/Reputation Standing Progression", definition: "Standing with one or more factions accumulates over time, unlocking deeper access, goods, or story content." },
          { label: "Seasonal Content Rotation", definition: "Content is introduced, retired, and rotated in on a recurring schedule, giving players a reason to return." },
          { label: "Achievement/Milestone Unlock Chain", definition: "Completing achievements or milestones unlocks further content, titles, or cosmetic rewards over the long term." },
          { label: "Legacy/Inheritance System", definition: "Elements from a completed or failed run carry forward to benefit future runs, common in roguelike meta-progression." },
          { label: "Crafting Recipe Unlock Progression", definition: "New crafting recipes are gradually discovered or unlocked as the player advances through the game over time." },
          { label: "Cosmetic Unlock Progression", definition: "Purely visual customization options accumulate and unlock as a long-term reward track separate from power." },
          { label: "Guild/Clan Progression", definition: "A player's guild or clan levels up collectively based on member contributions, unlocking shared benefits." },
          { label: "Leaderboard/Ranked Ladder Progression", definition: "The player's competitive rank persists and shifts across many matches on a long-term ladder." },
          { label: "World State Persistence", definition: "Player actions permanently and cumulatively reshape the world's state across sessions rather than resetting." },
          { label: "New Game Plus Difficulty Ladder", definition: "Completing the game unlocks a harder replay tier, which can often be repeated into further escalating tiers." },
          { label: "Mastery/Proficiency Tracks", definition: "Individual weapons, characters, or classes each have their own long-term experience track that unlocks perks as it levels." },
          { label: "Endgame Loop", definition: "A distinct set of systems and activities becomes the primary long-term loop once the main campaign is complete." },
        ],
      },
      {
        id: "social_loop",
        label: "Social Loop",
        options: [
          { label: "Trading/Marketplace Exchange", definition: "Players exchange items, currency, or resources directly with one another or through a shared marketplace." },
          { label: "Leaderboard Competition", definition: "Players compete indirectly by having their scores or achievements ranked against one another on a shared board." },
          { label: "Co-op Run/Party Play", definition: "A group of players tackle content together in real time, sharing objectives and outcomes." },
          { label: "Competitive Ranked Ladder", definition: "Players face off directly in matches that adjust a persistent, comparative rank between them." },
          { label: "Guild/Clan Membership", definition: "Players join a persistent social group that provides shared goals, chat, and collective benefits." },
          { label: "Player-vs-Player Dueling", definition: "Two players engage in a direct, often optional, one-on-one contest outside of the main progression path." },
          { label: "Gifting System", definition: "Players can send items, currency, or resources to one another as a goodwill or relationship-building gesture." },
          { label: "Social Visiting", definition: "Players can visit and interact with each other's persistent spaces, such as bases, farms, or homes." },
          { label: "Cooperative Raid/Group Content", definition: "A larger group of players coordinates to complete high-difficulty content that requires multiple participants." },
          { label: "Spectator Mode", definition: "Players can watch other players' matches or sessions in real time without directly participating." },
          { label: "Mentorship/Referral System", definition: "Experienced players are rewarded for guiding or recruiting new players into the game." },
          { label: "Alliance/Diplomacy System", definition: "Players or groups can formally ally, negotiate, or declare against one another within the game's social structure." },
          { label: "Community Events", definition: "The wider player base works, competes, or contributes together toward a shared, server-wide goal." },
          { label: "Player-Run Economy", definition: "Prices, supply, and demand for goods are driven primarily by player activity rather than fixed vendor rates." },
          { label: "Chat/Communication Systems", definition: "Players communicate directly through text, voice, or emotes as a core part of the social experience." },
          { label: "Reputation/Trust Rating Among Players", definition: "Other players can rate or review a given player's behavior, building a visible trust or reputation score." },
          { label: "Team-Based Objective Play", definition: "Players are grouped into teams that must cooperate toward a shared objective against another team." },
          { label: "Content Sharing", definition: "Players can create and share user-generated content, such as levels, mods, or designs, with the wider community." },
          { label: "Matchmaking-Based Grouping", definition: "Players are automatically grouped together by the system based on skill, role, or preferences for a session." },
          { label: "Rivalry System", definition: "The game tracks a persistent, recurring opponent for the player, framing repeated encounters as an ongoing rivalry." },
        ],
      },
    ],
  },
  {
    id: "characters",
    title: "Character Descriptions and Abilities",
    isCharacterSection: true,
    characterFields: [
      { key: "Name", multiline: false },
      { key: "Role/Archetype", multiline: false },
      { key: "Personality", multiline: true },
      { key: "Stat System", multiline: false },
      { key: "Abilities", multiline: true },
      { key: "Progression", multiline: true },
      { key: "Narrative Role", multiline: true },
      { key: "Balancing Notes", multiline: true },
    ],
  },
  {
    id: "world",
    title: "Level/World Design Overview",
    subsections: [
      {
        id: "world_structure",
        label: "World Structure",
        options: [
          { label: "Linear", definition: "A single, fixed path from start to finish with little or no deviation, used to control pacing and story order precisely." },
          { label: "Open World", definition: "A large, freely traversable continuous space the player can explore in almost any order with minimal gating." },
          { label: "Hub-and-Spoke", definition: "A central hub area connects to multiple discrete levels or zones that the player enters and exits individually." },
          { label: "Metroidvania (Interconnected)", definition: "A single sprawling map where new abilities or keys unlock shortcuts and previously inaccessible areas, encouraging backtracking." },
          { label: "Procedurally Generated", definition: "Levels or maps are assembled algorithmically at runtime rather than hand-authored, producing a different layout each playthrough." },
          { label: "Semi-Open / Zone-Based", definition: "The world is split into large, mostly open zones that are unlocked or connected sequentially rather than forming one continuous space." },
          { label: "Sandbox", definition: "A structure-light space built around player-driven systems (building, simulation, emergent play) rather than an authored critical path." },
          { label: "Level Select / Mission-Based", definition: "Discrete, self-contained levels or missions are chosen from a menu or map screen rather than travelled to in-world." },
          { label: "Branching / Non-Linear Path", definition: "The critical path forks into multiple routes or orderings the player can choose between, often converging again later." },
          { label: "Overworld with Dungeons", definition: "A traversable overworld map connects self-contained dungeons or instanced areas — the classic action-adventure structure." },
          { label: "Nodal Map", definition: "Locations are represented as connected nodes on an abstract map, and the player travels node-to-node rather than through continuous space." },
          { label: "Room-Based / Roguelike Floors", definition: "The world is built from discrete rooms or floors, often randomized, cleared one at a time before the player progresses." },
          { label: "Corridor / Tunnel", definition: "A narrow, mostly single-direction path with tightly controlled sightlines and encounters, common in linear shooters." },
          { label: "Persistent World (Shared/MMO)", definition: "A continuous, always-running world shared by many players simultaneously, persisting state between sessions." },
          { label: "Vertical Structure (Tower/Descent)", definition: "Progression is structured along a single vertical axis, climbing or descending through stacked levels." },
          { label: "Interconnected Hubs", definition: "Multiple hub areas are themselves connected to one another, layering the hub-and-spoke model." },
          { label: "District-Based / City Structure", definition: "The world is divided into named districts or neighborhoods, each with its own theme, tone, or unlock gate." },
          { label: "Island-Based / Archipelago", definition: "Discrete islands or landmasses are connected by travel — boat, portal, or flight — across open water or void." },
          { label: "Layered / Onion Structure", definition: "Concentric rings or layers surround a central point, with progression moving inward or outward through each layer." },
          { label: "Voxel / User-Generated World", definition: "The world is built — and often modifiable — from block-like units, frequently authored or altered by players themselves." },
          { label: "Arena-Based", definition: "Discrete, bounded combat spaces are the unit of world structure, with little or no traversal between encounters." },
          { label: "Time-Loop Structure", definition: "The same space is revisited repeatedly within a resetting time loop, with player knowledge — not new geography — driving progress." },
          { label: "Multiverse / Parallel Worlds", definition: "Multiple distinct versions of the same or related space exist and are traversed or compared against one another." },
        ],
      },
      {
        id: "level_flow",
        label: "Level Flow",
        options: [
          { label: "Linear Flow", definition: "A single, uninterrupted path through the level with no branching, so encounters and pacing occur in one fixed order." },
          { label: "Branching Flow", definition: "Paths diverge at one or more points into distinct routes that later reconverge before the level's end." },
          { label: "Parallel Path Flow", definition: "Multiple mutually exclusive routes let the player pick one path without ever crossing or rejoining the others." },
          { label: "Loop Flow", definition: "The level's path curves back on itself, returning the player near earlier areas from a new angle or elevation." },
          { label: "Hub-Based Flow", definition: "A central room or junction within the level branches out to sub-objectives, looping back to the hub between each." },
          { label: "Gauntlet Flow", definition: "Continuous, escalating challenges with little or no downtime between encounters, testing sustained performance." },
          { label: "Rising Action (Crescendo) Flow", definition: "Intensity builds gradually and steadily from the level's start toward a climactic finish." },
          { label: "Peak-and-Valley Flow", definition: "High-intensity encounters alternate with deliberate lulls or rest points, creating a rhythm of tension and release." },
          { label: "Combat–Puzzle Alternation", definition: "The level alternates between combat encounters and puzzle-solving segments in a repeating pattern." },
          { label: "Exploration-to-Confrontation Flow", definition: "An open exploration segment funnels into a fixed, high-stakes encounter such as a boss fight." },
          { label: "Backtrack/Unlock Flow", definition: "The level requires revisiting earlier sections with a newly acquired ability or key to reach previously blocked areas." },
          { label: "Wave-Based Flow", definition: "Progress is gated by discrete waves of enemies, with a breather or reward beat between each wave." },
          { label: "Checkpoint-Segmented Flow", definition: "The level is broken into discrete segments divided by checkpoints or save points, each with its own mini-arc." },
          { label: "Chase/Pursuit Flow", definition: "Forward momentum is continuous and time-pressured, as the player flees or pursues something with no chance to backtrack." },
          { label: "Stealth Flow", definition: "Pacing is driven by patrol timing and controlled visibility, alternating between careful waiting and short bursts of movement." },
          { label: "Vertical Flow (Ascent/Descent)", definition: "The level's progression is organized primarily along a vertical axis, climbing or descending through it." },
          { label: "Funnel Flow", definition: "The level opens with wide, open exploration that progressively narrows toward a single fixed objective or exit." },
          { label: "Bottleneck Flow", definition: "Deliberate chokepoints force all paths to converge at specific moments regardless of the route taken to reach them." },
          { label: "Escort/Companion Flow", definition: "Pacing is tied to protecting or guiding an NPC or object through the level at a pace it dictates." },
          { label: "Set-Piece (Scripted Sequence) Flow", definition: "Player-controlled sections are interspersed with scripted, cinematic moments that punctuate the pacing." },
          { label: "Free-Roam Interlude Flow", definition: "An otherwise structured level includes an open, objective-light segment before returning to structured progression." },
          { label: "Boss Rush Flow", definition: "The level consists of consecutive boss or mini-boss encounters with minimal traversal or downtime between them." },
          { label: "Non-Linear Objective Flow", definition: "A set of objectives within the level can be completed in any order the player chooses." },
          { label: "Time-Pressure Flow", definition: "An overall time limit governs pacing, forcing decisions about which paths or optional content to skip." },
        ],
      },
      {
        id: "env_storytelling",
        label: "Environmental Storytelling",
        options: [
          { label: "Ruined Battlefields", definition: "Wreckage, craters, or scattered equipment imply a past conflict occurred at this location." },
          { label: "Abandoned Camps", definition: "Left-behind belongings and cold campfires suggest inhabitants who departed suddenly or long ago." },
          { label: "Graffiti / Notes", definition: "Handwritten or painted messages left by characters convey backstory, warnings, or personality directly." },
          { label: "Lighting Cues", definition: "The color, intensity, or direction of light is used deliberately to signal mood, danger, or safety." },
          { label: "Audio Logs", definition: "Recorded voice or sound clips found in the world deliver narrative context the player chooses to engage with." },
          { label: "Corpse/Skeleton Placement", definition: "Positioned remains imply what happened at a location without any explicit narration." },
          { label: "Diegetic Text (Signs, Posters, Labels)", definition: "In-world signage or writing conveys setting, faction, or historical context as a natural part of the environment." },
          { label: "Environmental Wear and Damage", definition: "Physical deterioration of structures implies age, past conflict, or long-term neglect." },
          { label: "Staged Tableau", definition: "Objects and bodies are arranged intentionally to imply a specific frozen moment or event to the observant player." },
          { label: "Architectural Style Shift", definition: "A change in building style or material signals a shift in culture, era, or faction control between areas." },
          { label: "Scavenged/Repurposed Objects", definition: "Items reused for unintended purposes imply resourcefulness, scarcity, or desperation in that setting." },
          { label: "Environmental Audio Cues", definition: "Ambient sound reinforces the history or mood of a location without any dialogue or text." },
          { label: "Photographs/Personal Effects", definition: "Personal items left behind humanize a location's former inhabitants and hint at their individual stories." },
          { label: "Color Palette Shift", definition: "A deliberate change in color scheme signals a tonal or narrative transition as the player moves between areas." },
          { label: "Weather/Atmospheric Symbolism", definition: "Weather conditions are used symbolically to reflect the narrative tone or events of a location." },
          { label: "Blood Trails/Physical Evidence", definition: "Directional or scattered evidence implies movement, struggle, or an unseen event that occurred nearby." },
          { label: "Silhouette/Statue Iconography", definition: "Large-scale imagery or statues communicate ideology, history, or power structures at a glance." },
          { label: "Environmental Progression Decay", definition: "The same location is shown in different states of decay or change across the story's timeline." },
          { label: "Hidden/Optional Detail", definition: "Small, easily-missed details reward observant players with additional context beyond the main narrative." },
          { label: "Juxtaposition of Elements", definition: "Two contrasting objects or scenes are placed together to imply irony, tragedy, or thematic contrast." },
        ],
      },
      {
        id: "landmarks_nav",
        label: "Landmarks and Navigation",
        options: [
          { label: "Minimap", definition: "A small, always-visible map in the corner of the screen shows the player's immediate surroundings." },
          { label: "Compass", definition: "An on-screen directional strip shows nearby points of interest relative to the player's current facing." },
          { label: "Waypoint Markers", definition: "Player-placed or system-generated markers highlight a specific destination on the map and HUD." },
          { label: "Visual Landmarks", definition: "Distinct, recognizable structures or terrain features help players orient themselves without relying on UI." },
          { label: "Fast Travel Points", definition: "Discovered locations can be instantly traveled to again from anywhere, skipping traversal entirely." },
          { label: "Objective Marker/Quest Pin", definition: "An on-screen or on-map indicator points directly toward the player's current active objective." },
          { label: "Breadcrumb Trail", definition: "A visible path, such as light, particles, or footprints, actively guides the player toward a destination." },
          { label: "Landmark Silhouette", definition: "A large, distinct structure visible from a distance helps players orient themselves across an open space." },
          { label: "Directional Audio Cue", definition: "Sound is used positionally to hint at the direction of a nearby point of interest or danger." },
          { label: "Overworld Map Screen", definition: "A separate, zoomed-out map view shows the wider world and marks locations the player has discovered." },
          { label: "Signposting (In-World Signs)", definition: "Physical signs placed within the world point toward locations or directions, in-fiction." },
          { label: "Color-Coded Zones", definition: "Distinct color palettes per region help players visually recognize which area of the world they're currently in." },
          { label: "Vertical Landmark (Tower/Spire)", definition: "A tall, consistently visible structure serves as a reliable point of reference across a wide area." },
          { label: "NPC Guide/Escort Navigation", definition: "A companion character actively leads the player on foot toward a destination." },
          { label: "Environmental Funnel", definition: "Level geometry itself, such as lighting or architecture, subtly guides players toward the intended path without UI." },
          { label: "Discoverable Points of Interest", definition: "Unmarked locations only appear on the map once the player has physically discovered them." },
          { label: "Journal/Quest Log Cross-Reference", definition: "The quest log links directly back to map locations, letting players jump from objective text to its position." },
          { label: "Camera-Assisted Framing", definition: "The game camera subtly angles or pans to draw the player's attention toward the intended path or objective." },
          { label: "Persistent HUD Direction Indicator", definition: "An always-visible on-screen arrow or marker continuously points toward the player's current goal." },
          { label: "Landmark-Based Fast Travel Unlock", definition: "Fast travel points are unlocked specifically by physically discovering their corresponding landmark first." },
        ],
      },
      {
        id: "encounter_design",
        label: "Encounter Design",
        options: [
          { label: "Ambush Encounters", definition: "Enemies are hidden or concealed and initiate combat by surprise once the player enters a trigger area." },
          { label: "Wave-Based Combat", definition: "Enemies arrive in discrete, successive waves rather than all at once, pacing the fight over time." },
          { label: "Puzzle-Gated Rooms", definition: "Progress past the encounter requires solving a puzzle in addition to, or instead of, defeating enemies." },
          { label: "Boss Arenas", definition: "A dedicated, self-contained space is built specifically around a single major boss encounter." },
          { label: "Scripted Set-Piece Encounter", definition: "A tightly choreographed encounter combines combat with scripted events for cinematic spectacle." },
          { label: "Optional Side Encounter", definition: "A non-mandatory encounter off the critical path offers extra risk and reward for players who seek it out." },
          { label: "Escort Encounter", definition: "Combat occurs while the player must simultaneously protect an accompanying NPC or object." },
          { label: "Elite/Mini-Boss Encounter", definition: "A single empowered enemy, tougher than standard foes but short of a full boss, tests the player mid-level." },
          { label: "Environmental Hazard Encounter", definition: "The primary challenge of the encounter comes from environmental dangers rather than direct enemy combatants." },
          { label: "Stealth Encounter", definition: "The intended solution to the encounter is avoidance or subterfuge rather than direct confrontation." },
          { label: "Puzzle-Combat Hybrid Encounter", definition: "Combat and puzzle-solving are combined within the same encounter space, often solved simultaneously." },
          { label: "Horde/Swarm Encounter", definition: "The player faces a large number of individually weak enemies simultaneously, rather than a few strong ones." },
          { label: "Reinforcement Encounter", definition: "Additional enemies arrive mid-fight to escalate an encounter that is already in progress." },
          { label: "Timed Encounter", definition: "The encounter must be resolved within a fixed time limit or it ends in failure or an altered outcome." },
          { label: "Multi-Phase Boss Encounter", definition: "A single boss fight is structured into distinct phases, each with different attack patterns or arena states." },
          { label: "Arena Encounter (Locked Room)", definition: "The player is sealed into a space, often by closing doors or barriers, until the encounter is fully resolved." },
          { label: "Ranged/Cover-Based Encounter", definition: "The encounter design emphasizes exchanging fire from behind cover at range rather than close engagement." },
          { label: "Ambient/Random Encounter", definition: "Encounters occur unpredictably during traversal rather than at fixed, deliberately authored points." },
          { label: "Social/Dialogue Encounter", definition: "The encounter is resolved primarily through conversation or persuasion rather than combat." },
          { label: "Chained Encounter", definition: "Multiple encounters occur back-to-back with minimal recovery time between them, testing sustained resource management." },
        ],
      },
      {
        id: "blockout_refs",
        label: "Blockout References",
        options: [
          { label: "Top-Down Sketch", definition: "A rough overhead drawing lays out a level's shape, rooms, and connections before any geometry is built." },
          { label: "Greybox Screenshot", definition: "A screenshot of untextured placeholder geometry captures a space's scale and layout during early iteration." },
          { label: "3D Blockout Model", definition: "A simplified three-dimensional model represents the level's core geometry and spatial relationships." },
          { label: "Flow Diagram", definition: "A diagram maps the intended path and branching structure a player will take through the level." },
          { label: "Isometric Sketch", definition: "A pitched-angle drawing shows the layout and relative heights of a space at a glance." },
          { label: "Bubble Diagram", definition: "Rough circles and connecting lines represent rooms or zones and their relationships before a detailed layout exists." },
          { label: "Paper Prototype", definition: "A physical or simple digital layout tests spatial pacing and structure before any 3D geometry is built." },
          { label: "Whitebox Walkthrough Video", definition: "A recorded playthrough of the unfinished blockout demonstrates pacing and flow to the wider team." },
          { label: "Heatmap Overlay", definition: "A visual overlay shows where players moved, died, or lingered during playtesting of the blockout." },
          { label: "Elevation/Cross-Section Diagram", definition: "A side-on view shows the vertical relationships between different areas of a level." },
          { label: "Callout-Annotated Screenshot", definition: "A blockout screenshot is marked up with notes explaining the intended function of specific areas." },
          { label: "Encounter Placement Map", definition: "A top-down diagram marks planned enemy, item, and event locations before any final art pass." },
          { label: "Scale Reference Model", definition: "A blockout includes placeholder character-sized geometry to validate proportions and spacing." },
          { label: "Pacing Timeline Chart", definition: "A linear chart maps the intended tension or difficulty against the physical position in the level." },
          { label: "Modular Kit Layout", definition: "A blockout is built entirely from reusable modular pieces to test how a kit will support a full level." },
          { label: "Navmesh/AI Pathing Overlay", definition: "A visualization of the AI navigation mesh confirms enemies and companions can traverse the space as intended." },
          { label: "Comparison Overlay (Before/After)", definition: "A blockout screenshot is compared directly against the final art pass to track intended fidelity." },
          { label: "VR/First-Person Walkthrough", definition: "A first-person pass through the blockout validates scale and pacing from the actual player perspective." },
        ],
      },
    ],
  },
  {
    id: "controls",
    title: "Control Schemes",
    subsections: [
      {
        id: "input_mapping",
        label: "Input Mapping",
        options: [
          { label: "Controller Layout", definition: "A predefined mapping of gamepad buttons and sticks to specific in-game actions." },
          { label: "Keyboard/Mouse Layout", definition: "A predefined mapping of keyboard keys and mouse input to specific in-game actions." },
          { label: "Touch Controls", definition: "On-screen virtual buttons, sticks, or gestures serve as the primary input method on touchscreen devices." },
          { label: "Remappable Bindings", definition: "Players can reassign which physical input triggers each in-game action to suit their own preference." },
          { label: "Gamepad Analog Stick Mapping", definition: "Continuous analog stick input is mapped to variable-speed or variable-intensity actions rather than fixed on/off ones." },
          { label: "D-Pad/Digital Input Mapping", definition: "Discrete directional input is mapped to fixed, non-variable actions such as menu navigation." },
          { label: "Motion Control Mapping", definition: "Physical device movement, such as tilting or gesturing, is mapped directly to an in-game action." },
          { label: "Voice Command Mapping", definition: "Spoken commands are recognized and mapped to specific in-game actions." },
          { label: "Adaptive Trigger/Haptic Input", definition: "Variable resistance or force on a controller's triggers is mapped to context-sensitive feedback or input depth." },
          { label: "Hotbar/Quick-Slot Mapping", definition: "A fixed set of items or abilities is bound to a dedicated row of easily accessible inputs." },
          { label: "Modifier Key Combo Mapping", definition: "Holding a secondary key alters the function of a primary input, expanding the available action set." },
          { label: "Gesture-Based Mapping", definition: "Drawn or swiped gestures on a touchscreen or trackpad are mapped to specific commands." },
          { label: "Split-Screen/Local Co-op Mapping", definition: "Multiple physical controllers are simultaneously mapped to separate on-screen characters." },
          { label: "Accessibility Remapping", definition: "Inputs can be reconfigured or consolidated to support players with limited mobility or dexterity, such as one-handed play." },
          { label: "Legacy/Classic Control Scheme", definition: "An alternate mapping mimics the control scheme of an earlier game or established genre convention." },
          { label: "Simultaneous Multi-Input Mapping", definition: "Multiple input devices, such as keyboard and controller, can be used interchangeably or together within the same session." },
          { label: "Context-Layered Input Mapping", definition: "The same physical input maps to a different action depending on which menu or mode is currently active." },
          { label: "Radial/Pie Menu Input Mapping", definition: "A held input opens a radial menu where directional stick or mouse movement selects from multiple mapped options." },
        ],
      },
      {
        id: "context_sensitivity",
        label: "Context Sensitivity",
        options: [
          { label: "Shared Interact/Pickup/Talk Button", definition: "A single button performs whichever of interact, pick up, or talk is contextually valid at the moment." },
          { label: "Context-Sensitive Sprint/Dodge", definition: "The same input performs a sprint or a dodge depending on the player's current movement state or situation." },
          { label: "Aim-Dependent Actions", definition: "An input's effect changes depending on whether the player is currently aiming, such as switching from a light to a heavy attack." },
          { label: "State-Dependent Action Mapping", definition: "The same button performs a different action depending on the player character's current state, such as standing versus crouching." },
          { label: "Proximity-Triggered Prompt", definition: "A contextual action prompt only appears and becomes usable when the player is near a valid target." },
          { label: "Terrain-Sensitive Movement", definition: "Movement input automatically adapts its animation and behavior based on the surface or terrain type beneath the player." },
          { label: "Target-Lock Dependent Actions", definition: "Certain actions change behavior, or only become available, while a target is actively locked on." },
          { label: "Combo-State Sensitivity", definition: "An input performs a different move depending on the current step of an ongoing attack combo." },
          { label: "Vehicle vs. On-Foot Context Switch", definition: "The same control inputs perform entirely different actions depending on whether the player is in a vehicle or on foot." },
          { label: "Environmental Object Context", definition: "Interacting with different object types, such as a ladder, door, or lever, automatically triggers the appropriate context-specific animation." },
          { label: "Combat vs. Exploration Mode Switch", definition: "Input behavior changes depending on whether the game has flagged the player as currently being in or out of combat." },
          { label: "Held vs. Tapped Input Distinction", definition: "The same button produces a different result depending on whether it is tapped briefly or held down." },
          { label: "Multi-Function Analog Stick", definition: "Pushing the same stick performs a different function depending on the current context, such as menu navigation versus movement." },
          { label: "Auto-Context Camera Switching", definition: "The camera automatically adjusts its behavior or angle based on the currently active contextual action." },
          { label: "Menu vs. Gameplay Input Overlap", definition: "The same physical input performs a different action depending on whether a menu or HUD element currently has focus." },
        ],
      },
      {
        id: "feedback",
        label: "Feedback",
        options: [
          { label: "Haptic Feedback", definition: "Controller vibration communicates an in-game event to the player through physical sensation." },
          { label: "Animation Confirmation", definition: "A dedicated character animation plays to visually confirm that an action has successfully occurred." },
          { label: "Sound Cues", definition: "A distinct sound effect plays to confirm that an action, hit, or event has occurred." },
          { label: "Screen Shake", definition: "The camera view briefly shakes to emphasize the impact or intensity of a significant event." },
          { label: "Visual VFX Confirmation", definition: "A particle or graphical effect plays to confirm that an action has successfully registered." },
          { label: "UI Flash/Highlight", definition: "A brief flash or highlight on a UI element confirms a change in state, such as taking damage or gaining an item." },
          { label: "Damage Numbers", definition: "Numeric values appear on-screen to confirm the exact amount of damage or healing dealt by an action." },
          { label: "Hit-Stop/Freeze Frame", definition: "The game briefly pauses on impact to emphasize the weight and significance of an action." },
          { label: "Controller Rumble Pattern", definition: "Distinct vibration patterns communicate different types of events without requiring the player to look at the screen." },
          { label: "Color Flash Overlay", definition: "A full-screen color tint briefly appears to signal a specific state change, such as low health." },
          { label: "Voice Line/Bark Confirmation", definition: "A character voice line acknowledges a specific action or event as it occurs." },
          { label: "Camera Shake/Punch", definition: "The camera briefly shifts or punches inward in reaction to a significant impact or event." },
          { label: "Cursor/Reticle Feedback", definition: "The aiming reticle or cursor changes appearance to confirm a valid target or a successful hit." },
          { label: "Progress Bar/Meter Fill", definition: "A visible bar fills or drains to confirm the ongoing progress of an action over time." },
          { label: "Environmental Reaction Feedback", definition: "The game world itself visibly reacts, such as objects breaking or scattering, to confirm an action's impact." },
          { label: "Music Stinger", definition: "A short musical cue plays to punctuate a significant moment or a successful action." },
        ],
      },
      {
        id: "camera_controls",
        label: "Camera Controls",
        options: [
          { label: "Fixed Camera", definition: "The camera occupies a predetermined position and angle that the player cannot directly control." },
          { label: "Free Camera", definition: "The player has direct, unrestricted control over the camera's orientation and, often, its position." },
          { label: "Over-the-Shoulder", definition: "The camera is positioned just behind and above the character's shoulder, common in third-person action games." },
          { label: "Top-Down", definition: "The camera looks directly or near-directly downward at the player and the surrounding space." },
          { label: "Cinematic Cutscene Camera", definition: "The camera follows a scripted, film-like path and framing specifically during non-interactive story sequences." },
          { label: "First-Person Camera", definition: "The camera is placed at the character's eye level, showing the world entirely from their point of view." },
          { label: "Side-Scrolling Camera", definition: "The camera is locked to a fixed lateral plane, following the player horizontally through a 2D-style space." },
          { label: "Isometric Camera", definition: "The camera is fixed at a consistent angled overhead perspective throughout gameplay." },
          { label: "Dynamic Auto-Framing Camera", definition: "The camera automatically adjusts its position and angle to keep relevant action in frame." },
          { label: "Rail/On-Path Camera", definition: "The camera follows a predetermined path independent of direct player control." },
          { label: "Lock-On/Target Camera", definition: "The camera automatically orients to keep a locked-on target within frame during an encounter." },
          { label: "Split-Screen Camera", definition: "Multiple simultaneous camera views are displayed on screen at once for different players." },
          { label: "Photo Mode Camera", definition: "A dedicated, player-controlled camera mode decoupled from gameplay allows freeform framing for screenshots." },
          { label: "Zoom-Dependent Camera", definition: "Camera distance and field of view can be adjusted by the player, zooming in or out from the subject." },
          { label: "Collision-Avoidant Camera", definition: "The camera automatically repositions itself to avoid clipping through walls or other obstacles." },
          { label: "Vehicle/Mount Camera", definition: "The camera adjusts its position and behavior specifically when the player is controlling a vehicle or mount." },
        ],
      },
    ],
  },
  {
    id: "progression",
    title: "Progression and Reward Systems",
    subsections: [
      { id: "progression_types", label: "Progression Types", options: plain(["Linear Leveling", "Skill Trees", "Gear-Based", "Narrative Unlocks", "Hybrid"]) },
      { id: "reward_schedule", label: "Reward Schedule", options: plain(["Fixed Rewards", "Variable / Random Rewards", "Milestone Rewards", "Daily Rewards"]) },
      { id: "reward_types", label: "Reward Types", options: plain(["Cosmetic", "Mechanical (Power)", "Narrative Unlock", "Social Status"]) },
      { id: "pacing_curve", label: "Pacing Curve", options: plain(["Steady Linear Curve", "Steep Early, Flat Late", "Flat Early, Steep Late", "Spiky (Boss Spikes)"]) },
      { id: "player_agency", label: "Player Agency", options: plain(["Free Specialization", "Fixed Progression Path", "Respec Allowed"]) },
      { id: "retention_hooks", label: "Retention Hooks", options: plain(["Daily Login Rewards", "Battle Pass", "Achievements", "Seasonal Events"]) },
    ],
  },
];

export default initialSections;
