/* ============================================================
   SCHEMA — the single source of truth for the GDD Builder.
   Add a new object to `initialSections`, or a new entry to any
   `subsections` array, and the UI + generated document pick it
   up automatically — no other code changes needed.
   ============================================================ */
// Helper: turn a plain string list into {label, definition} objects.
// Used for subsections that don't have researched definitions yet —
// definition starts empty, so no tooltip shows until one is added.
const plain = (labels) => labels.map((label) => ({ label, definition: "" }));

const initialSections = [
  {
    id: "mechanics",
    title: "Gameplay Mechanics",
    subsections: [
      {
        id: "core_mechanics",
        label: "Core Mechanics",
        options: [
          { label: "Movement (Walk/Run)", definition: "Basic locomotion allowing the player to traverse the game space at variable speed." },
          { label: "Jump", definition: "A vertical traversal action that clears gaps, obstacles, or reaches higher ground." },
          { label: "Melee Attack", definition: "A close-range offensive action using direct-contact weapons or unarmed strikes." },
          { label: "Ranged Attack", definition: "An offensive action that damages targets at a distance using projectiles or hitscan weapons." },
          { label: "Block/Parry", definition: "A defensive action that mitigates or negates incoming damage when timed or held correctly." },
          { label: "Dodge/Evade", definition: "A quick directional movement that avoids incoming damage or attacks, often with brief invulnerability." },
          { label: "Sprint", definition: "A temporary speed boost to movement, typically limited by a stamina resource." },
          { label: "Crouch/Prone", definition: "Lowering the character's stance to reduce visibility, fit through spaces, or improve accuracy." },
          { label: "Climb", definition: "Vertical or angled traversal along surfaces such as ladders, walls, or ledges." },
          { label: "Swim", definition: "Movement through liquid environments, often governed by different controls than movement on land." },
          { label: "Interact", definition: "A general-purpose action for engaging with objects, NPCs, or the environment, such as opening or activating something." },
          { label: "Grab/Carry", definition: "Picking up and physically moving objects or characters within the world." },
          { label: "Aim", definition: "Directing a weapon or tool precisely before or during an action, typically affecting accuracy." },
          { label: "Reload", definition: "Restocking ammunition or a limited resource for a weapon or tool before it can be used again." },
          { label: "Aerial Mobility (Double Jump/Air Dash)", definition: "Extended mid-air movement options that let the player alter trajectory or gain height after leaving the ground." },
          { label: "Grapple/Hook", definition: "A traversal mechanic that pulls the player toward, or lets them swing from, a fixed anchor point." },
          { label: "Stealth/Sneak", definition: "Moving while minimizing detection by enemies or sensors, usually tied to noise level or visibility." },
          { label: "Build/Place", definition: "Constructing or placing structures, objects, or terrain pieces within the world." },
          { label: "Craft", definition: "Combining materials or components according to a recipe to create a new item." },
          { label: "Gather/Harvest", definition: "Collecting resources from the environment, such as plants, ore, or loot." },
          { label: "Trade/Barter", definition: "Exchanging items, currency, or resources with NPCs or other players." },
          { label: "Dialogue Choice", definition: "Selecting from branching conversation options that affect narrative outcomes or relationships." },
          { label: "Cast/Channel Ability", definition: "Activating a spell or special ability, often requiring a resource cost, cooldown, or charge time." },
          { label: "Summon", definition: "Calling forth an ally, creature, or object to fight or assist alongside the player." },
          { label: "Transform/Shapeshift", definition: "Changing the player character's form, temporarily or permanently altering their abilities or stats." },
          { label: "Push/Pull", definition: "Physically manipulating objects in the environment by applying directional force." },
          { label: "Throw", definition: "Launching an item, weapon, or projectile at a target location." },
          { label: "Heal/Restore", definition: "Recovering health, resources, or a status condition through an item, ability, or timed action." },
          { label: "Drive/Pilot", definition: "Taking control of a vehicle, mount, or mechanized unit instead of moving the character directly." },
          { label: "Time Manipulation", definition: "Slowing, stopping, rewinding, or fast-forwarding time as a direct, player-triggered action." },
        ],
      },
      {
        id: "secondary_mechanics",
        label: "Secondary Mechanics",
        options: [
          { label: "Inventory Management", definition: "A system for storing, organizing, and equipping the items the player collects." },
          { label: "Crafting System", definition: "Combining materials or components to create new items, gear, or consumables." },
          { label: "Dialogue System", definition: "Structured conversations with NPCs, often including branching choices that affect outcomes." },
          { label: "Stealth Mechanics", definition: "Supporting systems for avoiding detection, such as noise meters, visibility indicators, or patrol patterns." },
          { label: "Skill Tree/Talent System", definition: "A branching set of unlockable upgrades or abilities the player chooses from over time." },
          { label: "Companion/Pet System", definition: "Managing an AI ally or creature that assists, follows, or can be commanded by the player." },
          { label: "Reputation/Faction System", definition: "Tracking the player's standing with groups or factions that changes how those groups behave toward them." },
          { label: "Relationship/Affinity System", definition: "Tracking individual NPC relationships that shift based on player choices, gifts, or dialogue." },
          { label: "Quest/Journal Log", definition: "A system for tracking active, completed, and available objectives." },
          { label: "Fast Travel", definition: "A shortcut system letting players instantly move between previously discovered locations." },
          { label: "Housing/Base Building", definition: "Player-owned spaces that can be customized, decorated, or expanded over time." },
          { label: "Mount/Vehicle System", definition: "Managing rideable creatures or vehicles used for faster or specialized traversal." },
          { label: "Weather/Day-Night Cycle", definition: "Environmental systems that change conditions over time and may affect visibility, enemy behavior, or available actions." },
          { label: "Economy/Currency System", definition: "Managing money or trade goods used to buy, sell, or upgrade throughout the game." },
          { label: "Shop/Vendor System", definition: "Interfaces for buying and selling items with NPC merchants or other players." },
          { label: "Cooking/Alchemy System", definition: "Combining ingredients according to recipes to create food, potions, or temporary buffs." },
          { label: "Enchanting/Upgrading System", definition: "Enhancing existing gear with additional stats, effects, or higher rarity tiers." },
          { label: "Photo Mode", definition: "A non-gameplay feature that lets players pause the action and compose or capture in-game scenes." },
          { label: "Codex/Lore Collection", definition: "Collectible in-world text or item entries that expand on the setting's backstory without affecting core progression." },
          { label: "Achievement/Trophy System", definition: "Tracking optional milestones or challenges that exist outside the main progression path." },
          { label: "Minigame System", definition: "Self-contained smaller games embedded within the larger game, such as lockpicking or fishing." },
          { label: "Emote/Social Gesture System", definition: "Non-verbal communication options for expressing emotion or interacting socially with other players." },
          { label: "Difficulty/Assist Options", definition: "Adjustable settings that modify the game's challenge level or improve accessibility." },
          { label: "Weapon/Gear Customization", definition: "Modifying the appearance or stats of equipment through attachments, skins, or visual dyes." },
          { label: "Party/Squad Management", definition: "Assembling and directing a group of characters as a coordinated unit." },
          { label: "Notoriety/Wanted System", definition: "Tracking escalating law-enforcement or NPC response based on the player's recent actions." },
          { label: "Map/Cartography System", definition: "Revealing, marking, or annotating a world map as the player explores it." },
        ],
      },
      {
        id: "mechanic_interactions",
        label: "Mechanic Interactions",
        options: [
          { label: "Elemental Combination", definition: "Two elemental effects (fire, water, electricity, ice, etc.) combine to produce a new effect distinct from either alone." },
          { label: "Environmental Combo", definition: "A mechanic is applied to the environment itself, producing a secondary effect such as spreading fire or flooding an area." },
          { label: "Status Effect Stacking", definition: "Multiple status effects applied to the same target combine, amplify, or interact to produce a compounded outcome." },
          { label: "Chain Reaction", definition: "Triggering one effect causes it to cascade outward, setting off further effects on nearby targets or objects." },
          { label: "Synergy Combo", definition: "Combining specific abilities or items causes their effects to mutually amplify one another beyond their individual value." },
          { label: "Counter/Weakness Interaction", definition: "A specific mechanic is deliberately strong against, or negated by, another in a rock-paper-scissors-style relationship." },
          { label: "Resource Conversion", definition: "Using one mechanic transforms one resource type into another, such as converting health into mana." },
          { label: "Tool-Environment Interaction", definition: "A mechanic-based tool produces a specific, designed reaction when used on a matching environmental object." },
          { label: "Momentum Transfer", definition: "Velocity or force generated by one mechanic carries over and affects the outcome of a subsequent action." },
          { label: "Trigger-Response Interaction", definition: "Performing one mechanic activates an automated response from another system, such as a trap or switch." },
          { label: "Crowd Control Combo", definition: "An immobilizing or disabling mechanic is paired with a damage or follow-up mechanic to guarantee its effect lands." },
          { label: "Physics-Based Interaction", definition: "Mechanics interact through simulated physics, such as force, gravity, or collision, rather than scripted rules." },
          { label: "Timing-Based Interaction", definition: "Performing inputs in sequence within a specific time window combines them into a distinct, higher-value result." },
          { label: "Resource Denial Interaction", definition: "One mechanic removes or blocks a resource that another mechanic, often an opponent's, depends on to function." },
          { label: "Multiplayer Synergy Combo", definition: "Two or more players' individually-controlled mechanics combine to create an effect neither could produce alone." },
          { label: "State Transformation Interaction", definition: "One mechanic changes the state of an object or character in a way that alters how other mechanics subsequently affect it." },
          { label: "Amplification Interaction", definition: "One mechanic increases the potency, duration, or area of another mechanic's effect." },
          { label: "Suppression Interaction", definition: "One mechanic reduces, delays, or disables the effectiveness of another mechanic while active." },
          { label: "Positional Interaction", definition: "The spatial relationship between two mechanics, such as flanking or backstabbing, changes the outcome of an action." },
          { label: "Cascading Failure Interaction", definition: "The failure of one mechanic triggers a negative chain of consequences across other interconnected systems." },
        ],
      },
      {
        id: "rules_constraints",
        label: "Rules and Constraints",
        options: [
          { label: "Stamina Limit", definition: "A depletable resource that restricts sustained physical actions until it regenerates." },
          { label: "Cooldown Timer", definition: "A fixed time delay required before an ability or action can be used again." },
          { label: "Ammo/Resource Limit", definition: "A finite consumable resource restricts how often a ranged or resource-based action can be performed." },
          { label: "Weight/Carry Limit", definition: "A cap on how much the player can carry before movement or actions are penalized." },
          { label: "Health/Life Limit", definition: "A finite health pool whose depletion ends the current attempt, life, or run." },
          { label: "Permadeath", definition: "Death is permanent and irreversible, typically ending the run or erasing progress entirely." },
          { label: "Time Limit", definition: "An action, encounter, or level must be completed within a fixed time window." },
          { label: "Action Point Limit", definition: "A per-turn budget of points restricts how many actions can be taken in a given turn." },
          { label: "Shared Resource Pool", definition: "Multiple abilities draw from, and are limited by, the same shared resource rather than independent ones." },
          { label: "Line of Sight Requirement", definition: "An action can only be performed if a clear, unobstructed sightline exists to the target." },
          { label: "Range Limit", definition: "An action can only affect targets within a fixed maximum distance." },
          { label: "Positional Requirement", definition: "An action requires the player to be in a specific location, stance, or facing to execute it." },
          { label: "Charge/Buildup Requirement", definition: "An action requires a period of charging or channeling before its effect is applied." },
          { label: "Cost/Currency Requirement", definition: "An action can only be performed if the player is able to pay an associated in-game cost." },
          { label: "Durability Limit", definition: "Equipment degrades with use and eventually breaks or becomes less effective." },
          { label: "Inventory Slot Limit", definition: "A fixed number of inventory slots restricts how many distinct items can be carried at once." },
          { label: "Level/Gear Gate", definition: "An action, item, or area is inaccessible until the player reaches a required level or gear threshold." },
          { label: "Fall Damage Rule", definition: "A rule defining whether, and how much, damage is inflicted when falling from height." },
          { label: "Friendly Fire Rule", definition: "A rule determining whether a player's actions can harm allies or teammates." },
          { label: "One-Life-Per-Run Rule", definition: "Progress resets to the start of the run upon death, though separate meta-progression may still persist." },
          { label: "Turn Order Constraint", definition: "Actions must occur in a fixed sequence determined by initiative or turn order rather than freely." },
          { label: "Sanity/Corruption Limit", definition: "A secondary resource that depletes or rises with use of certain mechanics, carrying negative consequences at its extreme." },
          { label: "Detection Threshold", definition: "A rule defining the point at which stealth-based actions fail and the player becomes noticed." },
          { label: "Global Cooldown", definition: "After using any ability, a brief shared window prevents using any other ability, regardless of its individual cooldown." },
          { label: "Difficulty-Scaled Constraint", definition: "A rule whose limits, such as damage, resources, or timers, shift based on the selected difficulty setting." },
        ],
      },
      { id: "edge_cases", label: "Edge Cases", options: plain(["Heal While Stunned?", "Attack While Reloading?", "Interact During Cutscene?", "Status Effects Stack?"]) },
    ],
  },
  {
    id: "loops",
    title: "Gameplay Loops",
    subsections: [
      { id: "core_loop", label: "Core Loop", options: plain(["Explore → Fight → Loot → Upgrade", "Plant → Tend → Harvest → Sell", "Scout → Plan → Execute → Extract"]) },
      { id: "macro_loop", label: "Macro Loop", options: plain(["Complete Level → Unlock Next", "Clear Dungeon → Boss Fight", "Win Match → Season Progress"]) },
      { id: "meta_loop", label: "Meta Loop", options: plain(["Unlock New Zones", "Prestige System", "Seasonal Content", "Skill Tree Mastery"]) },
      { id: "social_loop", label: "Social Loop", options: plain(["Trading", "Leaderboards", "Co-op Runs", "Competitive Ranking", "Guilds / Clans"]) },
    ],
  },
  {
    id: "characters",
    title: "Character Descriptions and Abilities",
    isCharacterSection: true,
    characterFields: [
      { key: "Name", multiline: false },
      { key: "Role/Archetype", multiline: false },
      { key: "Personality", multiline: true },
      { key: "Stat System", multiline: false },
      { key: "Abilities", multiline: true },
      { key: "Progression", multiline: true },
      { key: "Narrative Role", multiline: true },
      { key: "Balancing Notes", multiline: true },
    ],
  },
  {
    id: "world",
    title: "Level/World Design Overview",
    subsections: [
      {
        id: "world_structure",
        label: "World Structure",
        options: [
          { label: "Linear", definition: "A single, fixed path from start to finish with little or no deviation, used to control pacing and story order precisely." },
          { label: "Open World", definition: "A large, freely traversable continuous space the player can explore in almost any order with minimal gating." },
          { label: "Hub-and-Spoke", definition: "A central hub area connects to multiple discrete levels or zones that the player enters and exits individually." },
          { label: "Metroidvania (Interconnected)", definition: "A single sprawling map where new abilities or keys unlock shortcuts and previously inaccessible areas, encouraging backtracking." },
          { label: "Procedurally Generated", definition: "Levels or maps are assembled algorithmically at runtime rather than hand-authored, producing a different layout each playthrough." },
          { label: "Semi-Open / Zone-Based", definition: "The world is split into large, mostly open zones that are unlocked or connected sequentially rather than forming one continuous space." },
          { label: "Sandbox", definition: "A structure-light space built around player-driven systems (building, simulation, emergent play) rather than an authored critical path." },
          { label: "Level Select / Mission-Based", definition: "Discrete, self-contained levels or missions are chosen from a menu or map screen rather than travelled to in-world." },
          { label: "Branching / Non-Linear Path", definition: "The critical path forks into multiple routes or orderings the player can choose between, often converging again later." },
          { label: "Overworld with Dungeons", definition: "A traversable overworld map connects self-contained dungeons or instanced areas — the classic action-adventure structure." },
          { label: "Nodal Map", definition: "Locations are represented as connected nodes on an abstract map, and the player travels node-to-node rather than through continuous space." },
          { label: "Room-Based / Roguelike Floors", definition: "The world is built from discrete rooms or floors, often randomized, cleared one at a time before the player progresses." },
          { label: "Corridor / Tunnel", definition: "A narrow, mostly single-direction path with tightly controlled sightlines and encounters, common in linear shooters." },
          { label: "Persistent World (Shared/MMO)", definition: "A continuous, always-running world shared by many players simultaneously, persisting state between sessions." },
          { label: "Vertical Structure (Tower/Descent)", definition: "Progression is structured along a single vertical axis, climbing or descending through stacked levels." },
          { label: "Interconnected Hubs", definition: "Multiple hub areas are themselves connected to one another, layering the hub-and-spoke model." },
          { label: "District-Based / City Structure", definition: "The world is divided into named districts or neighborhoods, each with its own theme, tone, or unlock gate." },
          { label: "Island-Based / Archipelago", definition: "Discrete islands or landmasses are connected by travel — boat, portal, or flight — across open water or void." },
          { label: "Layered / Onion Structure", definition: "Concentric rings or layers surround a central point, with progression moving inward or outward through each layer." },
          { label: "Voxel / User-Generated World", definition: "The world is built — and often modifiable — from block-like units, frequently authored or altered by players themselves." },
          { label: "Arena-Based", definition: "Discrete, bounded combat spaces are the unit of world structure, with little or no traversal between encounters." },
          { label: "Time-Loop Structure", definition: "The same space is revisited repeatedly within a resetting time loop, with player knowledge — not new geography — driving progress." },
          { label: "Multiverse / Parallel Worlds", definition: "Multiple distinct versions of the same or related space exist and are traversed or compared against one another." },
        ],
      },
      {
        id: "level_flow",
        label: "Level Flow",
        options: [
          { label: "Linear Flow", definition: "A single, uninterrupted path through the level with no branching, so encounters and pacing occur in one fixed order." },
          { label: "Branching Flow", definition: "Paths diverge at one or more points into distinct routes that later reconverge before the level's end." },
          { label: "Parallel Path Flow", definition: "Multiple mutually exclusive routes let the player pick one path without ever crossing or rejoining the others." },
          { label: "Loop Flow", definition: "The level's path curves back on itself, returning the player near earlier areas from a new angle or elevation." },
          { label: "Hub-Based Flow", definition: "A central room or junction within the level branches out to sub-objectives, looping back to the hub between each." },
          { label: "Gauntlet Flow", definition: "Continuous, escalating challenges with little or no downtime between encounters, testing sustained performance." },
          { label: "Rising Action (Crescendo) Flow", definition: "Intensity builds gradually and steadily from the level's start toward a climactic finish." },
          { label: "Peak-and-Valley Flow", definition: "High-intensity encounters alternate with deliberate lulls or rest points, creating a rhythm of tension and release." },
          { label: "Combat–Puzzle Alternation", definition: "The level alternates between combat encounters and puzzle-solving segments in a repeating pattern." },
          { label: "Exploration-to-Confrontation Flow", definition: "An open exploration segment funnels into a fixed, high-stakes encounter such as a boss fight." },
          { label: "Backtrack/Unlock Flow", definition: "The level requires revisiting earlier sections with a newly acquired ability or key to reach previously blocked areas." },
          { label: "Wave-Based Flow", definition: "Progress is gated by discrete waves of enemies, with a breather or reward beat between each wave." },
          { label: "Checkpoint-Segmented Flow", definition: "The level is broken into discrete segments divided by checkpoints or save points, each with its own mini-arc." },
          { label: "Chase/Pursuit Flow", definition: "Forward momentum is continuous and time-pressured, as the player flees or pursues something with no chance to backtrack." },
          { label: "Stealth Flow", definition: "Pacing is driven by patrol timing and controlled visibility, alternating between careful waiting and short bursts of movement." },
          { label: "Vertical Flow (Ascent/Descent)", definition: "The level's progression is organized primarily along a vertical axis, climbing or descending through it." },
          { label: "Funnel Flow", definition: "The level opens with wide, open exploration that progressively narrows toward a single fixed objective or exit." },
          { label: "Bottleneck Flow", definition: "Deliberate chokepoints force all paths to converge at specific moments regardless of the route taken to reach them." },
          { label: "Escort/Companion Flow", definition: "Pacing is tied to protecting or guiding an NPC or object through the level at a pace it dictates." },
          { label: "Set-Piece (Scripted Sequence) Flow", definition: "Player-controlled sections are interspersed with scripted, cinematic moments that punctuate the pacing." },
          { label: "Free-Roam Interlude Flow", definition: "An otherwise structured level includes an open, objective-light segment before returning to structured progression." },
          { label: "Boss Rush Flow", definition: "The level consists of consecutive boss or mini-boss encounters with minimal traversal or downtime between them." },
          { label: "Non-Linear Objective Flow", definition: "A set of objectives within the level can be completed in any order the player chooses." },
          { label: "Time-Pressure Flow", definition: "An overall time limit governs pacing, forcing decisions about which paths or optional content to skip." },
        ],
      },
      { id: "env_storytelling", label: "Environmental Storytelling", options: plain(["Ruined Battlefields", "Abandoned Camps", "Graffiti / Notes", "Lighting Cues", "Audio Logs"]) },
      { id: "landmarks_nav", label: "Landmarks and Navigation", options: plain(["Minimap", "Compass", "Waypoint Markers", "Visual Landmarks", "Fast Travel Points"]) },
      { id: "encounter_design", label: "Encounter Design", options: plain(["Ambush Encounters", "Wave-Based Combat", "Puzzle-Gated Rooms", "Boss Arenas"]) },
      { id: "blockout_refs", label: "Blockout References", options: plain(["Top-Down Sketch", "Greybox Screenshot", "3D Blockout Model", "Flow Diagram"]) },
    ],
  },
  {
    id: "controls",
    title: "Control Schemes",
    subsections: [
      { id: "input_mapping", label: "Input Mapping", options: plain(["Controller Layout", "Keyboard/Mouse Layout", "Touch Controls", "Remappable Bindings"]) },
      { id: "context_sensitivity", label: "Context Sensitivity", options: plain(["Interact/Pickup/Talk (Shared Button)", "Context-Sensitive Sprint/Dodge", "Aim-Dependent Actions"]) },
      { id: "feedback", label: "Feedback", options: plain(["Haptic Feedback", "Animation Confirmation", "Sound Cues", "Screen Shake"]) },
      { id: "camera_controls", label: "Camera Controls", options: plain(["Fixed Camera", "Free Camera", "Over-the-Shoulder", "Top-Down", "Cinematic Cutscene Camera"]) },
    ],
  },
  {
    id: "progression",
    title: "Progression and Reward Systems",
    subsections: [
      { id: "progression_types", label: "Progression Types", options: plain(["Linear Leveling", "Skill Trees", "Gear-Based", "Narrative Unlocks", "Hybrid"]) },
      { id: "reward_schedule", label: "Reward Schedule", options: plain(["Fixed Rewards", "Variable / Random Rewards", "Milestone Rewards", "Daily Rewards"]) },
      { id: "reward_types", label: "Reward Types", options: plain(["Cosmetic", "Mechanical (Power)", "Narrative Unlock", "Social Status"]) },
      { id: "pacing_curve", label: "Pacing Curve", options: plain(["Steady Linear Curve", "Steep Early, Flat Late", "Flat Early, Steep Late", "Spiky (Boss Spikes)"]) },
      { id: "player_agency", label: "Player Agency", options: plain(["Free Specialization", "Fixed Progression Path", "Respec Allowed"]) },
      { id: "retention_hooks", label: "Retention Hooks", options: plain(["Daily Login Rewards", "Battle Pass", "Achievements", "Seasonal Events"]) },
    ],
  },
];

export default initialSections;
